return {
  'folke/snacks.nvim',
  priority = 1000,
  lazy = false,
  opts = {
    animate = { enabled = 'true', duration = 5, easing = 'linear', fps = 60 },
    bufdelete = { enabled = 'true' },
    dashboard = { enabled = 'true', example = 'compact_files' },
    debug = { enabled = 'false' },
    dim = { enabled = 'false' },
    explorer = { enabled = 'true' },
    git = { enabled = 'false' },
    gitbrowse = { enabled = 'false' },
    image = { enabled = 'false' },
    indent = { enabled = 'false' },
    input = { enabled = 'false' },
    layout = { enabled = 'false' },
    lazygit = { enabled = 'false' },
    notifier = { enabled = 'false' },
    notify = { enabled = 'false' },
    picker = { enabled = 'true' },
    profiler = { enabled = 'false' },
    quickfile = { enabled = 'false' },
    rename = { enabled = 'false' },
    scope = { enabled = 'false' },
    scratch = { enabled = 'false' },
    scroll = { enabled = 'false' },
    statuscolumn = { enabled = 'false' },
    terminal = { enabled = 'false' },
    toggle = { enabled = 'false' },
    util = { enabled = 'false' },
    win = { enabled = 'false' },
    words = { enabled = 'false' },
    zen = { enabled = 'false' },
  },
  keys = {},
}
